import Head from "next/head";

import { Container, Typography, Box, Button } from "@material-ui/core";

import ProTip from "../src/components/ProTip";
import Copyright from "../src/components/Copyright";

export default function Home() {
    return (
        <Container maxWidth="sm">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box my={4}>
                <Typography variant="h4" component="h1" gutterBottom>
                    Next.js example
                </Typography>
                <Button variant="contained">Contained</Button>
                <ProTip />
                <Copyright />
            </Box>
        </Container>
    );
}
